services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_SUPPORT: false
    image: satisfactory_webapp_image
    container_name: satisfactory_webapp_container
    env_file:
      - .env
    restart: always
    ports:
      - "${PORT_WEBAPP:-8501}:${PORT_WEBAPP:-8501}"
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - ./data/sqlite:/app/data/sqlite
    healthcheck:
      test: "curl -f http://localhost:${PORT_WEBAPP:-8501}/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
